version: "3"
services:
  server:
    build: .
    ports:
     - "7777:7777/udp"
     - "5000:5000/tcp"
    volumes:
     - C:/Users/Armadous/AstroneerServer/AstroneerServer/Saved:c:/astroneer/Astro/Saved